import { act, fireEvent, render, screen, cleanup } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { PikoMusicDialog } from "./PikoMusicDialog";
const state = vi.hoisted(() => ({ playback: { src: "/piko/world/audio/bgm/welcome-courtyard-01.mp3", playing: false, error: false }, mute: vi.fn(), select: vi.fn() }));
vi.mock("./piko-bgm", () => ({ usePikoSelection: () => null, usePikoPlayback: () => state.playback, setPikoMusicMuted: state.mute, selectPikoMusic: state.select }));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.clearAllMocks(); });
it("toggles the current song from its row and delays rotation until the arm lands", () => {
  vi.useFakeTimers();
  const props = { open: true, onOpenChange: vi.fn() };
  const { rerender } = render(<PikoMusicDialog {...props} />);
  expect(screen.getByText("Piko小镇原声OST")).toBeTruthy();
  expect(screen.queryByText("跟随地图")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "播放风栖初逢之庭" }));
  expect(state.mute).toHaveBeenLastCalledWith(false);
  state.playback = { ...state.playback, playing: true };
  rerender(<PikoMusicDialog {...props} />);
  const disc = () => document.querySelector<HTMLElement>('[style*="animation-play-state"]')!;
  expect(disc().style.animationPlayState).toBe("paused");
  act(() => vi.advanceTimersByTime(650));
  expect(disc().style.animationPlayState).toBe("running");
  fireEvent.click(screen.getByRole("button", { name: "暂停风栖初逢之庭" }));
  expect(state.mute).toHaveBeenLastCalledWith(true);
  state.playback = { ...state.playback, playing: false };
  rerender(<PikoMusicDialog {...props} />);
  expect(disc().style.animationPlayState).toBe("paused");
  state.playback = { ...state.playback, playing: true };
  rerender(<PikoMusicDialog {...props} />);
  act(() => vi.advanceTimersByTime(200));
  state.playback = { ...state.playback, playing: false };
  rerender(<PikoMusicDialog {...props} />);
  act(() => vi.advanceTimersByTime(650));
  expect(disc().style.animationPlayState).toBe("paused");
});
