import { afterEach, expect, it, vi } from "vitest";
import { startCourtyardMusic } from "./piko-bgm";
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
it("retries denied playback, fades in and releases on exit", async () => {
 vi.useFakeTimers();
 const audio = { volume: 1, loop: false, play: vi.fn().mockRejectedValueOnce(new Error("blocked")).mockResolvedValue(undefined), pause: vi.fn(), removeAttribute: vi.fn(), load: vi.fn() };
 vi.stubGlobal("Audio", class { constructor() { return audio; } });
 const stop = startCourtyardMusic();
 await Promise.resolve();
 document.dispatchEvent(new Event("pointerdown"));
 await Promise.resolve();
 vi.advanceTimersByTime(2000);
 expect(audio.volume).toBe(0.4);
 expect(audio.loop).toBe(true);
 document.dispatchEvent(new Event("piko-notification-sound"));
 vi.advanceTimersByTime(150);
 expect(audio.volume).toBe(0.18);
 vi.advanceTimersByTime(1800);
 expect(audio.volume).toBe(0.4);
 stop();
 vi.advanceTimersByTime(800);
 expect(audio.volume).toBe(0);
 expect(audio.removeAttribute).toHaveBeenCalledWith("src");
 document.dispatchEvent(new Event("pointerdown"));
 expect(audio.play).toHaveBeenCalledTimes(2);
});
it("ignores a stale play result after returning from the background", async () => {
 vi.useFakeTimers();
 let hidden = false;
 const visibility = vi.spyOn(document, "hidden", "get").mockImplementation(() => hidden);
 const resolvers: (() => void)[] = [];
 const audio = { volume: 0, play: vi.fn(() => new Promise<void>(resolve => resolvers.push(resolve))), pause: vi.fn(), removeAttribute: vi.fn(), load: vi.fn() };
 vi.stubGlobal("Audio", class { constructor() { return audio; } });
 const stop = startCourtyardMusic();
 hidden = true; document.dispatchEvent(new Event("visibilitychange"));
 hidden = false; document.dispatchEvent(new Event("visibilitychange"));
 resolvers[1](); await Promise.resolve();
 const pauses = audio.pause.mock.calls.length;
 resolvers[0](); await Promise.resolve();
 expect(audio.pause).toHaveBeenCalledTimes(pauses);
 vi.advanceTimersByTime(2000);
 expect(audio.volume).toBe(0.4);
 stop(); vi.advanceTimersByTime(800);
 visibility.mockRestore();
});
it("retries on interaction if the browser paused previously successful autoplay", async () => {
 vi.useFakeTimers();
 const audio = { volume: 0, paused: false, play: vi.fn().mockResolvedValue(undefined), pause: vi.fn(), removeAttribute: vi.fn(), load: vi.fn() };
 vi.stubGlobal("Audio", class { constructor() { return audio; } });
 const stop = startCourtyardMusic();
 await Promise.resolve();
 audio.paused = true;
 document.dispatchEvent(new Event("pointerdown"));
 await Promise.resolve();
 expect(audio.play).toHaveBeenCalledTimes(2);
 stop(); vi.advanceTimersByTime(800);
});
